# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MasonRIBsSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MasonRIBsSample
    pod 'SnapKit', '~> 5.0.0'
    pod 'RIBs', :git=> 'https://github.com/uber/RIBs', :tag => 'v0.10.0'
    pod 'RxCocoa'

end
